### ISSUE TITLE
No implementation found for method makeCall on channel flutter_twilio_voice

### ISSUE THREAD

**Issue by agussuhardi-dev** [eopeter/flutter_twilio_voice#1]
I run the results of the clone and I find errors like this

[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method makeCall on channel flutter_twilio_voice)

**Comment by martintadashi** [comment]
@agussuhardii  I'm having this same problem on android, you?

**Comment by eopeter** [comment]
The ToDo has Android Support. So Only iOS at the moment.

**Comment by uttam-laila** [comment]
The problem still exists.
I'm getting:
Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method makeCall on channel flutter_twilio_voice))
